### ISSUE TITLE
any help Ubuntu 18.10 and play video?

### ISSUE THREAD

**Issue by goodidea-kp** [wget/archlinux-package-java-openjfx#1]
I asked a question on Stackoverflow https://stackoverflow.com/questions/53502323/how-to-install-missing-libs-on-ubuntu-18-10-to-playback-video-using-openjfx-11

Any help?

**Comment by wget** [comment]
@goodidea-kp Answered on list. Your issue does NOT concern this package, nor Arch Linux.
Closing.
